### ISSUE TITLE
each 不支持map?

### ISSUE THREAD

**Issue by maxid** [aui/artTemplate#158]
each 不支持map?
var data = {list:{key1:value1,key2:value}};

{{each list as value}}
    {{value.key}}:{{value.value}}
{{/each}}

**Comment by aui** [comment]
支持，但你的逻辑写错了

**Comment by maxid** [comment]
嗯，正确的用法是
var data = {list:{key1:value1,key2:value}};

{{each list as value key}}
    {{key}}:{{value}}
{{/each}}

**Comment by xjf721** [comment]
请问arttemplate是否支持调用map中的属性？

**Comment by xjf721** [comment]
比如对象为：{userMap:{123:{user}}}
我要如何在arttemplate中取到这个key为123的对象
{{userMap[123]}}
