### ISSUE TITLE
原生版本循环生成一行两列，用精简版怎样实现?

### ISSUE THREAD

**Issue by maxid** [aui/artTemplate#159]
for ( var i = 0, len = list.length ; i<len ; i += 2 ) {
   var j=i+1;
   list[i];
   list[j];
}

**Comment by aui** [comment]
简洁版语法很简单，只能循环，不能精确控制。解决方案：提前给模板构造好特殊结构的数据

**Comment by maxid** [comment]
嗯，目前就是这样做 ...
