### ISSUE TITLE
版主在么，你好，我发现一个问题，谢谢

### ISSUE THREAD

**Issue by artw054104** [aui/artTemplate#175]
我用模板渲染的时候，如果是ajax获取的数据，就正常
如果是类似java页面直接获取的 比如
var 数据= ${orderlist} (jsp获取数据流

页面就会渲染出json数据，也就是显示一大串的json数据，找了好久的原因

**Comment by aui** [comment]
1. 请检查数据类型，要求是`Object`而不是`String`
2. 提 Issues 麻烦写好标题
