### ISSUE TITLE
模板如果放js文件中如何写？

### ISSUE THREAD

**Issue by yaotaiyang** [aui/artTemplate#176]
模板如果放在html中，可以用script标签来写，用id来表示，如果模板放在js代码中呢，如何写，如果render？

**Comment by aui** [comment]
可以用`textarea`标签。另外：模板中插入脚本浏览器不一定执行

**Comment by yaotaiyang** [comment]
不是这个意思，我是想把模板放到js文件当中，不想把js放入到模板中。比如：template("cur_id",{});这段代码回去页面中找id为cur_id的script标签，就是说我模板要在页面中写出来，放到script中，并且id为cur_id。如果我想把这段模板放到一个独立的js文件中呢？怎么处理呢？有好办法吗？

**Comment by aui** [comment]
<http://aui.github.io/artTemplate/demo/compile.html>
