### ISSUE TITLE
helper方法调用问题

### ISSUE THREAD

**Issue by EmiyaKiritsugu** [aui/artTemplate#177]
您好！我在项目中使用tmodjs编译模板，但是发现编译后的template.js文件中helper方法总是被解析成数据字段（$data.xxx），我使用的是原生语法，helper尝试过在模板和在页面里定义，都是一样的问题。是我使用的方式不对吗？

模板代码
\<td style="background-color: #e61110; color: #fff;"\>\<%test(summary.moudle4.d3)%\>\</td\>

helper注册代码
\<script type="text/javascript" src="tpls/build/template.js"\>\</script\>
\<script type="text/javascript"\>
    template.helper('test', function(content){
        return content.substring(0, content.indexOf(".") + 3);
    });
    document.getElementById('test1').innerHTML = template('1', data);
\</script\>

编译后的模板文件
template("1", function($data, $filename) {
    try {
        var $utils = this, $line = ($utils.$helpers, 0), $escape = $utils.$escape, summary =               $data.summary, test = $data.test, $out = "";
        return $out += ....,
        $line = 71, test(summary.moudle4.d3), $out += '\</td\> \</tr\> \</table\> \</div\> \<div class="row summary-item"\> \<div class="col-xs-10 col-xs-offset-1" ,
        ......

运行时异常
\<name\> 
Render Error 
\<message\> 
test is not a function
\<line\> 
71 
\<source\>
 \<td style="background-color: #e61110; color: #fff;"\>\<%test(summary.moudle4.d3)%\>\</td\>

**Comment by aui** [comment]
helpers是需要打包进去的，请阅读tmodjs文档。
