### ISSUE TITLE
使用简明语法时，有好方法可以将模板写到纯js文件中吗？

### ISSUE THREAD

**Issue by yaotaiyang** [aui/artTemplate#181]
上次发的怎么不见了……使用简明语法时，有好方法可以将模板写到纯js文件中吗，比如我有个dialog.js文件，该文件中有对应的js模板，以及对应的js逻辑，模板放到html中的时候，如 <pre><code> 
&lt;script type="text/html" id="temp"&gt; &lt;/script&gt;  
var html = template("temp",{});</code></pre> 
如果放到js文件中，就没有id了，模板有好的书写方式吗？

**Comment by yaotaiyang** [comment]
http://aui.github.io/artTemplate/demo/compile.html 
自己贴上来把，demo地址，不过不是很优雅……

**Comment by aui** [comment]
<http://github.com/aui/tmodjs>
