### ISSUE TITLE
简洁语法模式不支持原生JS算法？

### ISSUE THREAD

**Issue by ferguson123123** [aui/artTemplate#182]
#### Error: Cannot read property 'ceil' of undefined

管道语法模式也不支持，难道非要使用helper来调用原声的JS函数方法？

**Comment by hwoarangzk** [comment]
有时候确实会遇到莫名其妙的错误。。。比如一些内置的对象找不到，就像这里的Math，不知道为啥。。。只能在compile的时候传进去。。。

**Comment by aui** [comment]
不支持访问全局对象的成员。解决方案参考文档关于辅助方法的描述

**Comment by hwoarangzk** [comment]
我是用了template.helper('Math', Math);的，大部分时间都没问题，但确实遇到过一两次，找不到Math对象的问题

**Comment by aui** [comment]
辅助方法需要在编译过程之前加载
