### ISSUE TITLE
多级属性的问题

### ISSUE THREAD

**Issue by rickel** [aui/artTemplate#184]
data = [
  {"id":1,"name":"test1","unit":{"id":1,"cname":"公斤"}},
  {"id":3,"name":"test2","unit":{"id":2,"cname":"斤"}}
];

请问这样的json如何进行模板调用，我按照如下方法调用没法正确显示
template("ProductsListTmpl", { Products: data });
{{each Products as product i}}
  {{product.name}} - {{product.unit.id}} 
{{/each}}

提示错误：Cannot read property 'id' of undefined

请指教，谢谢。

**Comment by aui** [comment]
我的测试结果是可以的，你可以检查你代码的``Products``最终是否按照预期结构
