### ISSUE TITLE
each时调用外层的数据可以吗？

### ISSUE THREAD

**Issue by nikittaa** [aui/artTemplate#189]
例：var data = {
		title : 'HELLO WORLD',
		isAdmin : true,
		list : ['新闻','军事','历史','政治']
	};
      在each list时：{{each list}} {{$value}}</li>{{/each}} ,调用到与list同级的title(在each内部), 可以实现吗？语法是?
       还是我不得不先把title放到list中，再调用each?
期待回复，谢谢！

**Comment by wangmeijian** [comment]
同问

**Comment by FengZeming** [comment]
跟我问的问题一样  期待作者赶快回答哟 这个问题真的是大问题 开发中会用到

**Comment by yaotaiyang** [comment]
我用过了，可以调用

**Comment by nikittaa** [comment]
@yaotaiyang 请问语法是？能否给个例子？

**Comment by aui** [comment]
{{title}}

**Comment by FengZeming** [comment]
<ul>

	{{each $data.list}} {{$value | listaddNum:num}} {{include './content' $value}} {{/each}}
	<div class="clear-box"></div>
</ul>
我居然是这么解决的  ........................ 绕了一个打圈圈   利用辅助方法  把num添加给当前变量

**Comment by FengZeming** [comment]
我才发现问题跟你的不同  我的是在子模板里 调用 主模板里的 某个变量  API里说 include 第三个参数 不加需要传递到子模板的变量的时候 是可以用到主模板里的 但是不好使呀

**Comment by yaotaiyang** [comment]
我也是直接就能取到
