### ISSUE TITLE
同一个模板，数据结构不同，如何渲染？

### ISSUE THREAD

**Issue by wangmeijian** [aui/artTemplate#192]
如数据是这样时，正常渲染：
	var data = {
		name:"template",
		sex:"boy"
	}
当数据是这样时，如何在{{}}内动态指定模板渲染数据为data.temp？
	var data = {
		temp:{
			name:"template",
			sex:"boy"
		}
	}

**Comment by aui** [comment]
这是控制器应该做的事情，应该在逻辑中来传递不同数据（模板也有 if 语句）
