### ISSUE TITLE
简洁语法中能用 for 循环吗？

### ISSUE THREAD

**Issue by ciaoca** [aui/artTemplate#195]
例如在原生语法，循环 7 - 12
<%for (var i=7;i<12;i++) {%>
  <div><%=i%></div>
<%}%>
只是想要循环出某一段数字，例如时间
在简洁语法中能直接实现吗？
还是必须要定义好[7,8,9,10,11,12]，再用 each 遍历？

**Comment by aui** [comment]
两个语法不能混写

**Comment by ciaoca** [comment]
那么简洁语法中除了 each 以外，还有 for 这样的语法吗？
