### ISSUE TITLE
无法在chrome插件中运行

### ISSUE THREAD

**Issue by dingyaguang117** [aui/artTemplate#230]
在chrome插件中运行会出错，无论template里面写什么（甚至空）都会报语法错误
```
Template Error

<temp>
function anonymous($data,$filename) {'use strict';var $utils=this,$helpers=$utils.$helpers,$out='';return new String($out);}

<filename>
basic-info-template2

<name>
Syntax Error
```

**Comment by dingyaguang117** [comment]
在 manifest 里面加上下面这行就好了，是chrome安全策略不允许支持eval

"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"

**Comment by zenoven** [comment]
我勒个擦。。。同样的问题，怎么调试都没找到问题，原来是Chrome插件机制的限制。。。哭晕在厕所。。。
