### ISSUE TITLE
关于artTemplate弹出新页面的问题

### ISSUE THREAD

**Issue by doukai** [aui/artTemplate#247]
问题是这样的：artTemplate是一个单页应用，我想知道有没有办法能让artTemplate支持新页面的弹出，即：模板文件是在新的窗口里，而js却在原来的窗口里，有这种实现的可能吗？谢谢

**Comment by aui** [comment]
这是非常基础的知识了。你可以通过`top`或`parent`访问到不同`window`的对象，进而进行你要的操作。这和模板引擎无关
