### ISSUE TITLE
数据反向到对象

### ISSUE THREAD

**Issue by tigerokkk** [aui/artTemplate#248]
把数据对象写到网页上用artTemplate很方便。但使用input编辑数据后，把数据再写回到对象上会很麻烦。
是否可以让可编辑的input textarea能够反向写到对象上？

**Comment by aui** [comment]
那么久不能使用字符串模板引擎了，可以使用 angularjs 或者其他的 MVVM 框架

**Comment by yaotaiyang** [comment]
其实也可以曲线救国实现一下，比如在模板input输出的时候，把对应的数据通过字符串标记上来。或者也可以用变量做个对应关系，input有变化的时候，全局方法去修改对应的变量。

**Comment by tigerokkk** [comment]
我自己写了一个数据反向写到对象的办法，楼主可以看看是不是可以做为arttemplate标准的数据输入方法：

http://blog.csdn.net/okkk/article/details/50580860
