### ISSUE TITLE
用webpack打包

### ISSUE THREAD

**Issue by diamont1001** [aui/artTemplate#257]
我现在项目想用webpack打包，模板使用文件分开，比如a.tpl
想问下有没有一个模板loader可以让我直接require(./a.tpl)就可以拿到tpl的内容

**Comment by diamont1001** [comment]
已解决，用ejs-loader就可以了，require的时候如下语法：
var html = require('./test.tpl')();
html即可拿到test.tpl的内容

**Comment by l-zhi** [comment]
https://github.com/dorayx/arttemplate-loader 这个是官方的么？

**Comment by diamont1001** [comment]
其实，可以用ejs-loader
