### ISSUE TITLE
each 能否选择循环的次数？

### ISSUE THREAD

**Issue by JZLeung** [aui/artTemplate#315]
比如说，一个数组有10个数据，但是我只想要其中的5条，那么能不能只输出5条数据？

**Comment by 57006007** [comment]
for循环有 index ，可以通过index进行过滤嘛。

**Comment by JZLeung** [comment]
那性能会打折扣。。。

**Comment by 57006007** [comment]
如果只要其中几条
第一种方式：提前把数据归到一起，然后用template展示。
第二种方式：在template内部做循环时，通过数组的数据内容来判断是否显示。
第三种方式：可以用helper自己定义一个工具，然后用JS处理完数据后在template中展示。

**Comment by JZLeung** [comment]
好吧，谢谢了，已经使用原生的形式搞定了。谢谢。
