### ISSUE TITLE
外部文件，是如何音乐的

### ISSUE THREAD

**Issue by soody** [aui/artTemplate#326]
template('tpl/home/main', data)

这个是如何引用的，main是否是文件，文件后缀是html 还是 tpl，还是 htm

缺少例子，网络上也没有相关知识

**Comment by statickid** [comment]
我也想问这个来着，如果不能放到外部的js文件中，这个模板js几乎无法使用

**Comment by aui** [comment]
<https://github.com/aui/artTemplate#使用预编译>
