### ISSUE TITLE
简易语法模式下, 双目操作符似乎有些问题

### ISSUE THREAD

**Issue by dingjibang** [aui/artTemplate#331]
如
    {{ (flag ? text1 : text2) | formatText }}

根据flag, 使用不同的text, 并且调用helper "formatText" , 但是实际上并不会执行formatText这个helper

当然, 下面这种情况也无法执行
    {{ (flag ? text1 | formatText : text2 | formatText) }}

:( 可能简易的语法模式不支持这么写吧

**Comment by wmlgl** [comment]
简易语法里":"是用来传参数的

**Comment by dingjibang** [comment]
原来如此，谢谢qwq
